[package]
name = "internal_types"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"
description = "InfluxDB IOx internal types, shared between IOx instances"
readme = "README.md"

[dependencies]
arrow = { version = "5.0", features = ["prettyprint"] }
bytes = "1.0"
data_types = { path = "../data_types" }
hashbrown = "0.11"
futures = "0.3"
indexmap = "1.6"
itertools = "0.10.1"
object_store = { path = "../object_store" }
observability_deps = { path = "../observability_deps" }
snafu = "0.6"

[dev-dependencies]
arrow_util = { path = "../arrow_util" }
